import { useMemo, useState } from 'react';
import Hero from '../components/home/Hero';
import PromoBanner from '../components/home/PromoBanner';
import CategoryTabs from '../components/home/CategoryTabs';
import Filters from '../components/product/Filters';
import ProductGrid from '../components/product/ProductGrid';
import { ProductSkeletons } from '../components/common/Skeleton';
import { useStore } from '../context/StoreContext';
export default function Home() { const { categorias, subcategorias, productos, loading, error } = useStore(); const [filters, setFilters] = useState({ categoria:'all', subcategoria:'all', marca:'all', precioMax:'', oferta:false, nuevo:false, destacado:false, q:'' }); const currentSubs = filters.categoria === 'all' ? subcategorias : subcategorias.filter(s=>s.categoria_id===filters.categoria); const marcas = [...new Set(productos.map(p=>p.marca).filter(Boolean))]; const filtered = useMemo(()=>productos.filter(p => (filters.categoria==='all'||p.categoria_id===filters.categoria) && (filters.subcategoria==='all'||p.subcategoria_id===filters.subcategoria) && (filters.marca==='all'||p.marca===filters.marca) && (!filters.precioMax||p.precio<=Number(filters.precioMax)) && (!filters.oferta||p.oferta) && (!filters.nuevo||p.nuevo) && (!filters.destacado||p.destacado) && (!filters.q||`${p.nombre} ${p.descripcion} ${p.marca}`.toLowerCase().includes(filters.q.toLowerCase()))), [productos, filters]); return <><Hero/><PromoBanner/><section id="productos" className="section mt-16"><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="admin-label">Catálogo dinámico</p><h2 className="text-4xl font-black">Accesorios destacados</h2>{error && <p className="mt-2 text-sm text-red-600">{error}</p>}</div><input className="input max-w-md rounded-full" placeholder="Buscar por nombre, descripción, marca..." value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/></div><CategoryTabs categorias={categorias} selected={filters.categoria} onSelect={(id)=>setFilters({...filters,categoria:id,subcategoria:'all'})}/><div className="mt-6 grid gap-6 lg:grid-cols-[280px_1fr]"><Filters marcas={marcas} filters={filters} setFilters={setFilters} subcategorias={currentSubs}/>{loading ? <ProductSkeletons/> : <ProductGrid products={filtered}/>}</div></section><AutoSection id="ofertas" title="Ofertas" products={productos.filter(p=>p.oferta)} /><AutoSection title="Nuevos" products={productos.filter(p=>p.nuevo)} /><AutoSection title="Más vendidos" products={productos.filter(p=>p.destacado)} /></>; }
function AutoSection({id,title,products}) { if (!products.length) return null; return <section id={id} className="section mt-20"><div className="mb-6"><p className="admin-label">Automático desde Supabase</p><h2 className="text-3xl font-black">{title}</h2></div><ProductGrid products={products.slice(0,4)}/></section>; }
