import { useEffect, useState } from 'react';
import { isSupabaseConfigured } from '../services/supabaseClient';
import { adminList, deleteRow, upsertRow } from '../services/storeApi';
import { normalizeProduct, validateProduct } from '../utils/validators';
import { useStore } from '../context/StoreContext';
const emptyProduct = { nombre:'', descripcion:'', precio:'', precio_anterior:'', categoria_id:'', subcategoria_id:'', imagen_principal:'', imagenes:'', stock:0, nuevo:false, oferta:false, destacado:false, marca:'', activo:true, fecha:new Date().toISOString().slice(0,10) };
export default function AdminPage() { const { config, categorias, subcategorias, refresh } = useStore(); const [tab,setTab]=useState('productos'); const [rows,setRows]=useState([]); const [form,setForm]=useState(emptyProduct); const [message,setMessage]=useState(''); useEffect(()=>{ if(isSupabaseConfigured) adminList(tab).then(setRows).catch(e=>setMessage(e.message)); },[tab]); const save = async (table, payload) => { setMessage('Guardando...'); try { await upsertRow(table, payload); setMessage('Guardado correctamente'); setForm(table==='productos'?emptyProduct:{}); await refresh(); if(isSupabaseConfigured) setRows(await adminList(tab)); } catch(e){ setMessage(e.message); } };
 return <section className="section min-h-screen pt-32"><div className="mb-8"><p className="admin-label">Panel administrador</p><h1 className="text-4xl font-black">Gestionar ziX Store</h1><p className="mt-3 max-w-2xl text-black/55">Administra productos, categorías, subcategorías y configuración. Conecta Supabase en <code>.env</code> para guardar cambios reales.</p>{!isSupabaseConfigured && <div className="mt-4 rounded-2xl bg-amber-100 p-4 text-sm font-semibold text-amber-900">Modo demo: Supabase no está configurado, los formularios muestran la estructura pero no guardan.</div>}{message && <p className="mt-4 rounded-2xl bg-white p-3 text-sm font-bold">{message}</p>}</div><div className="mb-6 flex flex-wrap gap-2">{['productos','categorias','subcategorias','configuracion'].map(t=><button key={t} onClick={()=>{setTab(t); setForm(t==='productos'?emptyProduct:{});}} className={`rounded-full px-5 py-3 text-sm font-bold ${tab===t?'bg-ink text-white':'bg-white'}`}>{t}</button>)}</div>{tab==='productos' && <ProductForm form={form} setForm={setForm} categorias={categorias} subcategorias={subcategorias} onSave={()=>{ const payload=normalizeProduct(form); const v=validateProduct(payload); if(!v.valid) return setMessage(Object.values(v.errors).join(', ')); save('productos', payload); }}/>} {tab==='categorias' && <SimpleForm fields={['id','nombre','icono','orden','activo']} onSave={(payload)=>save('categorias', payload)} />} {tab==='subcategorias' && <SimpleForm fields={['id','categoria_id','nombre','orden','activo']} onSave={(payload)=>save('subcategorias', payload)} />} {tab==='configuracion' && <ConfigForm initial={config} onSave={(payload)=>save('configuracion', payload)} />}<AdminRows rows={rows} onEdit={setForm} onDelete={async(id)=>{await deleteRow(tab,id); setRows(await adminList(tab));}} /></section>; }
function ProductForm({form,setForm,categorias,subcategorias,onSave}) { const input=(k,props={})=><input className="input" placeholder={k} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})} {...props}/>; return <div className="glass mb-8 grid gap-4 rounded-[2rem] p-5 md:grid-cols-3">{input('id')}{input('nombre')}{input('marca')}{input('precio',{type:'number'})}{input('precio_anterior',{type:'number'})}{input('stock',{type:'number'})}<select className="input" value={form.categoria_id} onChange={e=>setForm({...form,categoria_id:e.target.value})}><option value="">Categoría</option>{categorias.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><select className="input" value={form.subcategoria_id} onChange={e=>setForm({...form,subcategoria_id:e.target.value})}><option value="">Subcategoría</option>{subcategorias.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select>{input('imagen_principal')}<textarea className="input md:col-span-2" placeholder="descripcion" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/><textarea className="input" placeholder="imagenes (una URL por línea)" value={form.imagenes} onChange={e=>setForm({...form,imagenes:e.target.value})}/>{['nuevo','oferta','destacado','activo'].map(k=><label key={k} className="font-bold"><input type="checkbox" checked={!!form[k]} onChange={e=>setForm({...form,[k]:e.target.checked})}/> {k}</label>)}<button className="btn-primary md:col-span-3" onClick={onSave}>Guardar producto</button></div>; }
function SimpleForm({fields,onSave}) { const [f,setF]=useState({activo:true}); return <div className="glass mb-8 grid gap-4 rounded-[2rem] p-5 md:grid-cols-3">{fields.map(k=> k==='activo'?<label key={k} className="font-bold"><input type="checkbox" checked={!!f[k]} onChange={e=>setF({...f,[k]:e.target.checked})}/> activo</label>:<input key={k} className="input" placeholder={k} value={f[k]??''} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<button className="btn-primary md:col-span-3" onClick={()=>onSave(f)}>Guardar</button></div>; }
function ConfigForm({initial,onSave}) { const [f,setF]=useState(initial||{}); const keys=['id','nombre_tienda','logo','banner','titulo_banner','subtitulo_banner','telefono','correo','facebook','instagram','tiktok','direccion','horario','tema','color_principal','color_secundario']; return <div className="glass mb-8 grid gap-4 rounded-[2rem] p-5 md:grid-cols-2">{keys.map(k=><input key={k} className="input" placeholder={k} value={f?.[k]??''} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<button className="btn-primary md:col-span-2" onClick={()=>onSave(f)}>Guardar configuración</button></div>; }
function AdminRows({rows,onEdit,onDelete}) { if(!rows?.length) return null; return <div className="overflow-hidden rounded-[2rem] bg-white"><div className="max-h-[520px] overflow-auto"><table className="w-full text-left text-sm"><tbody>{rows.map(r=><tr key={r.id} className="border-b"><td className="p-3 font-bold">{r.nombre||r.nombre_tienda||r.id}</td><td className="p-3 text-right"><button className="mr-3 font-bold" onClick={()=>onEdit(r)}>Editar</button><button className="font-bold text-red-600" onClick={()=>onDelete(r.id)}>Eliminar</button></td></tr>)}</tbody></table></div></div>; }
